version: '3.5'

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data   
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-management-api
    env_file: .env
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  pgdata:   
